/**
 * Suomenkieliset käännökset käyttäjäoikeus­matriisin Action-nimille ja kategorioille.
 *
 * Kun uusia actioneita lisätään eVakan koodipohjaan, niitä ei automaattisesti
 * käännetä — frontend käyttää fallbackina action-shortNamea. Tämä on tarkoituksellinen
 * suunnitteluvalinta: päivitykset ovat valinnaisia, eivätkä rikkomatta käännösten päivittämättömyys
 * tee koodikantaa epäjohdonmukaiseksi.
 *
 * Lähde:
 *   - kategoriaotsikot: eVakan i18n-tiedostot (frontend/src/lib-customizations/.../i18n/fi.tsx)
 *   - action-otsikot: systemaattisesti johdettu Action-nimen rakenteesta
 *     (verbiprefix + objekti) + valikoidut käsinmuotoiltavat
 *
 * Generoitu skriptillä .claude/roolimatriisi/build_labels.py.
 * Käsinmuokkaus tähän on OK — käännökset ovat staattisia, eivät uudelleen­generoinnin alaisia
 * jos rivit on tarkistettu manuaalisesti.
 */

export const CATEGORY_LABELS: Record<string, string> = {
  AbsenceApplication: "Poissaolohakemus",
  Application: "Hakemus",
  ApplicationNote: "Hakemusmuistiinpano",
  AssistanceAction: "Tukitoimi",
  AssistanceFactor: "Tuen tarpeen kerroin",
  AssistanceNeedDecision: "Tuen tarpeen päätös",
  AssistanceNeedPreschoolDecision: "Esiopetuksen tuen päätös",
  AssistanceNeedVoucherCoefficient: "Palvelusetelin tuen kerroin",
  Attachment: "Liite",
  BackupCare: "Varasijoitus",
  BackupPickup: "Varahakija",
  CalendarEvent: "Kalenteritapahtuma",
  CalendarEventTime: "Kalenteritapahtuman aika",
  Child: "Lapsi",
  ChildDailyNote: "Lapsen päivän muistiinpano",
  ChildDocument: "Lapsen asiakirja",
  ChildImage: "Lapsen kuva",
  ChildStickyNote: "Lapsen huomiotarra",
  ClubTerm: "Kerhokausi",
  DailyServiceTime: "Päivittäinen palveluaika",
  DaycareAssistance: "Varhaiskasvatuksen tuki",
  Decision: "Päätös",
  DocumentTemplate: "Asiakirjapohja",
  Employee: "Työntekijä",
  FamilyContact: "Perheen yhteyshenkilö",
  FeeAlteration: "Maksuoikaisu",
  FeeDecision: "Maksupäätös",
  FeeThresholds: "Maksun raja-arvot",
  FinanceDecisionHandler: "Talouspäätösten käsittelijä",
  FinanceNote: "Taloushuomautus",
  FosterParent: "Sijaisvanhempi",
  Global: "Yleinen",
  Group: "Ryhmä",
  GroupNote: "Ryhmämuistiinpano",
  GroupPlacement: "Ryhmäsijoitus",
  HolidayPeriod: "Lomakausi",
  Income: "Tulo",
  IncomeStatement: "Tuloilmoitus",
  Invoice: "Lasku",
  InvoiceCorrection: "Laskukorjaus",
  MessageAccount: "Viestitili",
  MobileDevice: "Mobiililaite",
  OtherAssistanceMeasure: "Muu tukitoimi",
  Pairing: "Mobiililaitepariutus",
  Parentship: "Lapsi-vanhempi-suhde",
  Partnership: "Puolisosuhde",
  Payment: "Maksu",
  PedagogicalDocument: "Pedagoginen asiakirja",
  Person: "Henkilö",
  Placement: "Sijoitus",
  PlacementPlan: "Sijoitussuunnitelma",
  PreschoolAssistance: "Esiopetuksen tuki",
  PreschoolTerm: "Esiopetuskausi",
  ServiceApplication: "Palveluhakemus",
  ServiceNeed: "Palveluntarve",
  ServiceVoucher: "Palveluseteli",
  ServiceVoucherValueDecision: "Palvelusetelin arvopäätös",
  Unit: "Yksikkö",
  VasuDocument: "Vasu",
  VasuTemplate: "Vasu-pohja",
  VoucherValueDecision: "Arvopäätös",
};

export const ACTION_LABELS: Record<string, string> = {
  "Action.AbsenceApplication.DECIDE": "Poissaolohakemus: päätä",
  "Action.AbsenceApplication.DECIDE_MAX_WEEK": "Poissaolohakemus: päätä (max week)",
  "Action.AbsenceApplication.READ": "Poissaolohakemus: lue",
  "Action.Application.ACCEPT_DECISION": "Hakemus: hyväksy päätös",
  "Action.Application.CANCEL": "Hakemus: peruuta",
  "Action.Application.CANCEL_PLACEMENT_PLAN": "Hakemus: peruuta sijoitussuunnitelma",
  "Action.Application.CONFIRM_DECISIONS_MAILED": "Hakemus: vahvista (decisions mailed)",
  "Action.Application.CREATE_NOTE": "Hakemus: luo muistiinpano",
  "Action.Application.CREATE_PLACEMENT_PLAN": "Hakemus: luo sijoitussuunnitelma",
  "Action.Application.MOVE_TO_WAITING_PLACEMENT": "Hakemus: siirrä (to waiting placement)",
  "Action.Application.READ": "Hakemus: lue",
  "Action.Application.READ_DECISION_DRAFT": "Hakemus: lue päätösluonnos",
  "Action.Application.READ_IF_HAS_ASSISTANCE_NEED": "Hakemus: lue (if has assistance need)",
  "Action.Application.READ_METADATA": "Hakemus: lue (metadata)",
  "Action.Application.READ_NOTES": "Hakemus: lue muistiinpanot",
  "Action.Application.READ_PLACEMENT_PLAN_DRAFT": "Hakemus: lue sijoitussuunnitelman luonnos",
  "Action.Application.READ_SERVICE_WORKER_ACCOUNT_MESSAGES": "Hakemus: lue (service worker account messages)",
  "Action.Application.READ_SPECIAL_EDUCATION_TEACHER_NOTES": "Hakemus: lue (special education teacher notes)",
  "Action.Application.REJECT_DECISION": "Hakemus: hylkää päätös",
  "Action.Application.RESPOND_TO_PLACEMENT_PROPOSAL": "Hakemus: vastaa sijoitusehdotukseen",
  "Action.Application.RETURN_TO_SENT": "Hakemus: palauta (to sent)",
  "Action.Application.SEND": "Hakemus: lähetä",
  "Action.Application.SEND_DECISIONS_WITHOUT_PROPOSAL": "Hakemus: lähetä (decisions without proposal)",
  "Action.Application.SEND_PLACEMENT_PROPOSAL": "Hakemus: lähetä (placement proposal)",
  "Action.Application.UPDATE": "Hakemus: päivitä",
  "Action.Application.UPDATE_DECISION_DRAFT": "Hakemus: päivitä päätösluonnos",
  "Action.Application.UPDATE_PLACEMENT_DRAFT": "Hakemus: päivitä (placement draft)",
  "Action.Application.UPLOAD_ATTACHMENT": "Hakemus: lataa liite",
  "Action.Application.VERIFY": "Hakemus: vahvista",
  "Action.Application.WITHDRAW_PLACEMENT_PROPOSAL": "Hakemus: peruuta sijoitusehdotus",
  "Action.ApplicationNote.DELETE": "Hakemusmuistiinpano: poista",
  "Action.ApplicationNote.UPDATE": "Hakemusmuistiinpano: päivitä",
  "Action.AssistanceAction.DELETE": "Tukitoimi: poista",
  "Action.AssistanceAction.READ": "Tukitoimi: lue",
  "Action.AssistanceAction.UPDATE": "Tukitoimi: päivitä",
  "Action.AssistanceFactor.DELETE": "Tuen tarpeen kerroin: poista",
  "Action.AssistanceFactor.READ": "Tuen tarpeen kerroin: lue",
  "Action.AssistanceFactor.UPDATE": "Tuen tarpeen kerroin: päivitä",
  "Action.AssistanceNeedVoucherCoefficient.DELETE": "Palvelusetelin tuen kerroin: poista",
  "Action.AssistanceNeedVoucherCoefficient.UPDATE": "Palvelusetelin tuen kerroin: päivitä",
  "Action.Attachment.DELETE_APPLICATION_ATTACHMENT": "Liite: poista hakemuksen liite",
  "Action.Attachment.DELETE_FEE_ALTERATION_ATTACHMENTS": "Liite: poista maksuoikaisun liitteet",
  "Action.Attachment.DELETE_INCOME_ATTACHMENT": "Liite: poista tuloliite",
  "Action.Attachment.DELETE_INCOME_STATEMENT_ATTACHMENT": "Liite: poista tuloselvityksen liite",
  "Action.Attachment.DELETE_INVOICE_ATTACHMENT": "Liite: poista (invoice attachment)",
  "Action.Attachment.DELETE_MESSAGE_CONTENT_ATTACHMENT": "Liite: poista (message content attachment)",
  "Action.Attachment.DELETE_ORPHAN_ATTACHMENT": "Liite: poista (orphan attachment)",
  "Action.Attachment.DELETE_PEDAGOGICAL_DOCUMENT_ATTACHMENT": "Liite: poista pedagogisen asiakirjan liite",
  "Action.Attachment.READ_APPLICATION_ATTACHMENT": "Liite: lue hakemuksen liite",
  "Action.Attachment.READ_FEE_ALTERATION_ATTACHMENT": "Liite: lue (fee alteration attachment)",
  "Action.Attachment.READ_INCOME_ATTACHMENT": "Liite: lue tuloliite",
  "Action.Attachment.READ_INCOME_STATEMENT_ATTACHMENT": "Liite: lue tuloselvityksen liite",
  "Action.Attachment.READ_INVOICE_ATTACHMENT": "Liite: lue (invoice attachment)",
  "Action.Attachment.READ_ORPHAN_ATTACHMENT": "Liite: lue (orphan attachment)",
  "Action.Attachment.READ_PEDAGOGICAL_DOCUMENT_ATTACHMENT": "Liite: lue pedagogisen asiakirjan liite",
  "Action.BackupCare.DELETE": "Varasijoitus: poista",
  "Action.BackupCare.UPDATE": "Varasijoitus: päivitä",
  "Action.BackupPickup.DELETE": "Varahakija: poista",
  "Action.BackupPickup.UPDATE": "Varahakija: päivitä",
  "Action.CalendarEvent.DELETE": "Kalenteritapahtuma: poista",
  "Action.CalendarEvent.READ": "Kalenteritapahtuma: lue",
  "Action.CalendarEvent.UPDATE": "Kalenteritapahtuma: päivitä",
  "Action.CalendarEventTime.DELETE": "Kalenteritapahtuman aika: poista",
  "Action.CalendarEventTime.UPDATE_RESERVATION": "Kalenteritapahtuman aika: päivitä (reservation)",
  "Action.Child.CREATE_ABSENCE": "Lapsi: luo poissaolo",
  "Action.Child.CREATE_ASSISTANCE_ACTION": "Lapsi: luo tukitoimi",
  "Action.Child.CREATE_ASSISTANCE_FACTOR": "Lapsi: luo tuen tarpeen kerroin",
  "Action.Child.CREATE_ASSISTANCE_NEED_VOUCHER_COEFFICIENT": "Lapsi: luo (assistance need voucher coefficient)",
  "Action.Child.CREATE_ATTENDANCE_RESERVATION": "Lapsi: luo läsnäolovaraus",
  "Action.Child.CREATE_BACKUP_CARE": "Lapsi: luo varasijoitus",
  "Action.Child.CREATE_BACKUP_PICKUP": "Lapsi: luo varahakija",
  "Action.Child.CREATE_CHILD_DECISION_DOCUMENT": "Lapsi: luo lapsen päätösasiakirja",
  "Action.Child.CREATE_CHILD_DOCUMENT": "Lapsi: luo lapsen asiakirja",
  "Action.Child.CREATE_DAILY_NOTE": "Lapsi: luo päivän muistiinpano",
  "Action.Child.CREATE_DAILY_SERVICE_TIME": "Lapsi: luo päivittäinen palveluaika",
  "Action.Child.CREATE_DAYCARE_ASSISTANCE": "Lapsi: luo varhaiskasvatuksen tuki",
  "Action.Child.CREATE_FEE_ALTERATION": "Lapsi: luo maksuoikaisu",
  "Action.Child.CREATE_OTHER_ASSISTANCE_MEASURE": "Lapsi: luo muu tukitoimi",
  "Action.Child.CREATE_PEDAGOGICAL_DOCUMENT": "Lapsi: luo pedagoginen asiakirja",
  "Action.Child.CREATE_PRESCHOOL_ASSISTANCE": "Lapsi: luo esiopetuksen tuki",
  "Action.Child.CREATE_STICKY_NOTE": "Lapsi: luo huomiotarra",
  "Action.Child.DELETE_ABSENCE": "Lapsi: poista poissaolo",
  "Action.Child.DELETE_ABSENCE_RANGE": "Lapsi: poista (absence range)",
  "Action.Child.DELETE_HOLIDAY_RESERVATIONS": "Lapsi: poista (holiday reservations)",
  "Action.Child.DELETE_IMAGE": "Lapsi: poista (image)",
  "Action.Child.READ": "Lapsi: lue",
  "Action.Child.READ_ABSENCES": "Lapsi: lue poissaolot",
  "Action.Child.READ_ABSENCE_APPLICATIONS": "Lapsi: lue (absence applications)",
  "Action.Child.READ_ADDITIONAL_INFO": "Lapsi: lue lisätiedot",
  "Action.Child.READ_APPLICATION": "Lapsi: lue hakemus",
  "Action.Child.READ_ASSISTANCE": "Lapsi: lue tuki",
  "Action.Child.READ_ASSISTANCE_ACTION": "Lapsi: lue tukitoimet",
  "Action.Child.READ_ASSISTANCE_FACTORS": "Lapsi: lue tuen kertoimet",
  "Action.Child.READ_ASSISTANCE_NEED_VOUCHER_COEFFICIENTS": "Lapsi: lue palvelusetelin tuen kertoimet",
  "Action.Child.READ_ATTENDANCE_REPORT": "Lapsi: lue (attendance report)",
  "Action.Child.READ_BACKUP_CARE": "Lapsi: lue varasijoitus",
  "Action.Child.READ_BACKUP_PICKUP": "Lapsi: lue varahakija",
  "Action.Child.READ_BASIC_INFO": "Lapsi: lue perustiedot",
  "Action.Child.READ_BLOCKED_GUARDIANS": "Lapsi: lue (blocked guardians)",
  "Action.Child.READ_CHILD_DOCUMENT": "Lapsi: lue lapsen asiakirja",
  "Action.Child.READ_DAILY_SERVICE_TIMES": "Lapsi: lue päivittäiset palveluajat",
  "Action.Child.READ_DAYCARE_ASSISTANCES": "Lapsi: lue varhaiskasvatuksen tuet",
  "Action.Child.READ_FAMILY_CONTACTS": "Lapsi: lue perheen yhteyshenkilöt",
  "Action.Child.READ_FEE_ALTERATIONS": "Lapsi: lue maksuoikaisut",
  "Action.Child.READ_FUTURE_ABSENCES": "Lapsi: lue tulevat poissaolot",
  "Action.Child.READ_GUARDIANS": "Lapsi: lue huoltajat",
  "Action.Child.READ_NON_RESERVABLE_RESERVATIONS": "Lapsi: lue (non reservable reservations)",
  "Action.Child.READ_ONGOING_ATTENDANCE": "Lapsi: lue (ongoing attendance)",
  "Action.Child.READ_OTHER_ASSISTANCE_MEASURES": "Lapsi: lue muut tukitoimet",
  "Action.Child.READ_PEDAGOGICAL_DOCUMENTS": "Lapsi: lue pedagogiset asiakirjat",
  "Action.Child.READ_PLACEMENT": "Lapsi: lue sijoitus",
  "Action.Child.READ_PRESCHOOL_ASSISTANCES": "Lapsi: lue esiopetuksen tuet",
  "Action.Child.READ_SENSITIVE_INFO": "Lapsi: lue arkaluonteiset tiedot",
  "Action.Child.READ_SERVICE_APPLICATIONS": "Lapsi: lue (service applications)",
  "Action.Child.READ_SERVICE_NEEDS": "Lapsi: lue palveluntarpeet",
  "Action.Child.UPDATE_ADDITIONAL_INFO": "Lapsi: päivitä lisätiedot",
  "Action.Child.UPDATE_FAMILY_CONTACT_DETAILS": "Lapsi: päivitä (family contact details)",
  "Action.Child.UPDATE_FAMILY_CONTACT_PRIORITY": "Lapsi: päivitä (family contact priority)",
  "Action.Child.UPDATE_NON_RESERVABLE_RESERVATIONS": "Lapsi: päivitä (non reservable reservations)",
  "Action.Child.UPLOAD_IMAGE": "Lapsi: lataa kuva",
  "Action.Child.UPSERT_CHILD_DATE_PRESENCE": "Lapsi: tallenna (child date presence)",
  "Action.ChildDailyNote.DELETE": "Lapsen päivän muistiinpano: poista",
  "Action.ChildDailyNote.UPDATE": "Lapsen päivän muistiinpano: päivitä",
  "Action.ChildDocument.ACCEPT_DECISION": "Lapsen asiakirja: hyväksy päätös",
  "Action.ChildDocument.ANNUL_DECISION": "Lapsen asiakirja: mitätöi päätös",
  "Action.ChildDocument.ARCHIVE": "Lapsen asiakirja: arkistoi",
  "Action.ChildDocument.DELETE": "Lapsen asiakirja: poista",
  "Action.ChildDocument.DOWNLOAD": "Lapsen asiakirja: lataa",
  "Action.ChildDocument.DOWNLOAD_VERSION": "Lapsen asiakirja: lataa (version)",
  "Action.ChildDocument.NEXT_STATUS": "Lapsen asiakirja: seuraava tila",
  "Action.ChildDocument.PREV_STATUS": "Lapsen asiakirja: edellinen tila",
  "Action.ChildDocument.PROPOSE_DECISION": "Lapsen asiakirja: ehdota päätös",
  "Action.ChildDocument.PUBLISH": "Lapsen asiakirja: julkaise",
  "Action.ChildDocument.READ": "Lapsen asiakirja: lue",
  "Action.ChildDocument.READ_ACCEPTED_DECISIONS": "Lapsen asiakirja: lue (accepted decisions)",
  "Action.ChildDocument.READ_METADATA": "Lapsen asiakirja: lue (metadata)",
  "Action.ChildDocument.REJECT_DECISION": "Lapsen asiakirja: hylkää päätös",
  "Action.ChildDocument.UPDATE": "Lapsen asiakirja: päivitä",
  "Action.ChildDocument.UPDATE_DECISION_VALIDITY": "Lapsen asiakirja: päivitä päätöksen voimassaolo",
  "Action.ChildImage.DOWNLOAD": "Lapsen kuva: lataa",
  "Action.ChildStickyNote.DELETE": "Lapsen huomiotarra: poista",
  "Action.ChildStickyNote.UPDATE": "Lapsen huomiotarra: päivitä",
  "Action.ClubTerm.DELETE": "Kerhokausi: poista",
  "Action.ClubTerm.UPDATE": "Kerhokausi: päivitä",
  "Action.DailyServiceTime.DELETE": "Päivittäinen palveluaika: poista",
  "Action.DailyServiceTime.UPDATE": "Päivittäinen palveluaika: päivitä",
  "Action.DaycareAssistance.DELETE": "Varhaiskasvatuksen tuki: poista",
  "Action.DaycareAssistance.READ": "Varhaiskasvatuksen tuki: lue",
  "Action.DaycareAssistance.UPDATE": "Varhaiskasvatuksen tuki: päivitä",
  "Action.Decision.ARCHIVE": "Päätös: arkistoi",
  "Action.Decision.DOWNLOAD_PDF": "Päätös: lataa (pdf)",
  "Action.Decision.READ": "Päätös: lue",
  "Action.Decision.UPDATE_REASONING_LINKS": "Päätös: päivitä perustelulinkit",
  "Action.DocumentTemplate.COPY": "Asiakirjapohja: kopioi",
  "Action.DocumentTemplate.DELETE": "Asiakirjapohja: poista",
  "Action.DocumentTemplate.FORCE_UNPUBLISH": "Asiakirjapohja: pakota (unpublish)",
  "Action.DocumentTemplate.READ": "Asiakirjapohja: lue",
  "Action.DocumentTemplate.UPDATE": "Asiakirjapohja: päivitä",
  "Action.Employee.ACTIVATE": "Työntekijä: aktivoi",
  "Action.Employee.DEACTIVATE": "Työntekijä: deaktivoi",
  "Action.Employee.DELETE": "Työntekijä: poista",
  "Action.Employee.DELETE_DAYCARE_ROLES": "Työntekijä: poista (daycare roles)",
  "Action.Employee.READ_DETAILS": "Työntekijä: lue (details)",
  "Action.Employee.READ_OPEN_GROUP_ATTENDANCE": "Työntekijä: lue (open group attendance)",
  "Action.Employee.READ_OUT_OF_OFFICE": "Työntekijä: lue (out of office)",
  "Action.Employee.UPDATE_DAYCARE_ROLES": "Työntekijä: päivitä (daycare roles)",
  "Action.Employee.UPDATE_EMAIL": "Työntekijä: päivitä (email)",
  "Action.Employee.UPDATE_GLOBAL_ROLES": "Työntekijä: päivitä (global roles)",
  "Action.Employee.UPDATE_OUT_OF_OFFICE": "Työntekijä: päivitä (out of office)",
  "Action.Employee.UPDATE_STAFF_ATTENDANCES": "Työntekijä: päivitä henkilökunnan läsnäolot",
  "Action.FeeAlteration.DELETE": "Maksuoikaisu: poista",
  "Action.FeeAlteration.UPDATE": "Maksuoikaisu: päivitä",
  "Action.FeeAlteration.UPLOAD_ATTACHMENT": "Maksuoikaisu: lataa liite",
  "Action.FeeDecision.ARCHIVE": "Maksupäätös: arkistoi",
  "Action.FeeDecision.IGNORE": "Maksupäätös: ohita",
  "Action.FeeDecision.READ": "Maksupäätös: lue",
  "Action.FeeDecision.READ_METADATA": "Maksupäätös: lue (metadata)",
  "Action.FeeDecision.UNIGNORE": "Maksupäätös: kumoa ohitus",
  "Action.FeeDecision.UPDATE": "Maksupäätös: päivitä",
  "Action.FeeThresholds.UPDATE": "Maksun raja-arvot: päivitä",
  "Action.FinanceNote.DELETE": "Taloushuomautus: poista",
  "Action.FinanceNote.UPDATE": "Taloushuomautus: päivitä",
  "Action.FosterParent.DELETE": "Sijaisvanhempi: poista",
  "Action.FosterParent.UPDATE": "Sijaisvanhempi: päivitä",
  "Action.Global.APPLICATIONS_PAGE": "Hakemukset (sivu)",
  "Action.Global.CREATE_CLUB_TERM": "Yleinen: luo (club term)",
  "Action.Global.CREATE_DOCUMENT_TEMPLATE": "Yleinen: luo asiakirjapohja",
  "Action.Global.CREATE_DRAFT_INVOICES": "Yleinen: luo (draft invoices)",
  "Action.Global.CREATE_DRAFT_PAYMENTS": "Yleinen: luo (draft payments)",
  "Action.Global.CREATE_EMPLOYEE": "Yleinen: luo työntekijä",
  "Action.Global.CREATE_FEE_THRESHOLDS": "Yleinen: luo maksun raja-arvot",
  "Action.Global.CREATE_HOLIDAY_PERIOD": "Yleinen: luo lomakausi",
  "Action.Global.CREATE_HOLIDAY_QUESTIONNAIRE": "Yleinen: luo lomakysely",
  "Action.Global.CREATE_PAPER_APPLICATION": "Yleinen: luo (paper application)",
  "Action.Global.CREATE_PERSON": "Yleinen: luo (person)",
  "Action.Global.CREATE_PERSONAL_MOBILE_DEVICE_PAIRING": "Yleinen: luo (personal mobile device pairing)",
  "Action.Global.CREATE_PERSON_FROM_VTJ": "Yleinen: luo (person from vtj)",
  "Action.Global.CREATE_PRESCHOOL_TERM": "Yleinen: luo (preschool term)",
  "Action.Global.CREATE_UNIT": "Yleinen: luo yksikkö",
  "Action.Global.CREATE_VOUCHER_VALUE": "Yleinen: luo (voucher value)",
  "Action.Global.CUSTOMERS_PAGE": "Asiakkaat (sivu)",
  "Action.Global.DELETE_HOLIDAY_PERIOD": "Yleinen: poista lomakausi",
  "Action.Global.DELETE_HOLIDAY_QUESTIONNAIRE": "Yleinen: poista lomakysely",
  "Action.Global.DELETE_VOUCHER_VALUE": "Yleinen: poista (voucher value)",
  "Action.Global.DOCUMENT_TEMPLATES_PAGE": "Asiakirjapohjat (sivu)",
  "Action.Global.EMPLOYEES_PAGE": "Työntekijät (sivu)",
  "Action.Global.FEE_BASICS_PAGE": "Maksun perusteet (sivu)",
  "Action.Global.FEE_DECISIONS_PAGE": "Maksupäätökset (sivu)",
  "Action.Global.FETCH_INCOME_STATEMENTS_AWAITING_HANDLER": "Yleinen: hae käsittelijää odottavat tuloselvitykset",
  "Action.Global.FINANCE_BASICS_PAGE": "Maksun perusteet (sivu)",
  "Action.Global.FINANCE_PAGE": "Talous (sivu)",
  "Action.Global.HOLIDAY_AND_TERM_PERIODS_PAGE": "Loma- ja toimikaudet (sivu)",
  "Action.Global.MESSAGES_PAGE": "Viestit (sivu)",
  "Action.Global.MESSAGING_PAGE": "Viestintä (sivu)",
  "Action.Global.OUT_OF_OFFICE_PAGE": "Poissaolo (sivu)",
  "Action.Global.PERSONAL_MOBILE_DEVICE_PAGE": "Henkilökohtainen mobiililaite (sivu)",
  "Action.Global.PERSON_SEARCH_PAGE": "Henkilöhaku (sivu)",
  "Action.Global.PIN_CODE_PAGE": "PIN-koodi (sivu)",
  "Action.Global.PLACEMENT_TOOL": "Sijoitustyökalu",
  "Action.Global.READ_ACTIVE_HOLIDAY_QUESTIONNAIRES": "Yleinen: lue (active holiday questionnaires)",
  "Action.Global.READ_AROMI_ORDERS": "Yleinen: lue (aromi orders)",
  "Action.Global.READ_ASSISTANCE_ACTION_OPTIONS": "Yleinen: lue (assistance action options)",
  "Action.Global.READ_CHILD_DOCUMENT_DECISIONS_REPORT": "Yleinen: lue (child document decisions report)",
  "Action.Global.READ_CUSTOMER_FEES_REPORT": "Yleinen: lue (customer fees report)",
  "Action.Global.READ_DECISIONS_REPORT": "Yleinen: lue päätökset -raportti",
  "Action.Global.READ_DECISION_REASONINGS": "Yleinen: lue (decision reasonings)",
  "Action.Global.READ_DECISION_UNITS": "Yleinen: lue päätösyksiköt",
  "Action.Global.READ_DOCUMENT_TEMPLATE": "Yleinen: lue asiakirjapohja",
  "Action.Global.READ_DRAFT_OCCUPANCIES": "Yleinen: lue (draft occupancies)",
  "Action.Global.READ_DUPLICATE_PEOPLE_REPORT": "Yleinen: lue kaksoiskappaleet -raportti",
  "Action.Global.READ_EMPLOYEES": "Yleinen: lue työntekijät",
  "Action.Global.READ_ENDED_PLACEMENTS_REPORT": "Yleinen: lue päättyneet sijoitukset -raportti",
  "Action.Global.READ_FEE_THRESHOLDS": "Yleinen: lue maksun raja-arvot",
  "Action.Global.READ_FINANCE_DECISION_HANDLERS": "Yleinen: lue talouspäätösten käsittelijät",
  "Action.Global.READ_FUTURE_PRESCHOOLERS": "Yleinen: lue (future preschoolers)",
  "Action.Global.READ_HOLIDAY_PERIOD": "Yleinen: lue lomakausi",
  "Action.Global.READ_HOLIDAY_PERIODS": "Yleinen: lue lomakaudet",
  "Action.Global.READ_HOLIDAY_QUESTIONNAIRE": "Yleinen: lue lomakysely",
  "Action.Global.READ_HOLIDAY_QUESTIONNAIRES": "Yleinen: lue (holiday questionnaires)",
  "Action.Global.READ_INCOME_COEFFICIENT_MULTIPLIERS": "Yleinen: lue (income coefficient multipliers)",
  "Action.Global.READ_INCOME_TYPES": "Yleinen: lue tulotyypit",
  "Action.Global.READ_INCOMPLETE_INCOMES_REPORT": "Yleinen: lue (incomplete incomes report)",
  "Action.Global.READ_INVOICE_CODES": "Yleinen: lue laskutuskoodit",
  "Action.Global.READ_INVOICE_REPORT": "Yleinen: lue lasku-raportti",
  "Action.Global.READ_MISSING_HEAD_OF_FAMILY_REPORT": "Yleinen: lue puuttuva perhepäämies -raportti",
  "Action.Global.READ_NON_SSN_CHILDREN_REPORT": "Yleinen: lue ilman henkilötunnusta olevat lapset -raportti",
  "Action.Global.READ_PERSONAL_MOBILE_DEVICES": "Yleinen: lue (personal mobile devices)",
  "Action.Global.READ_PLACEMENT_COUNT_REPORT": "Yleinen: lue sijoitusmäärä-raportti",
  "Action.Global.READ_PLACEMENT_DESKTOP_DAYCARES": "Yleinen: lue (placement desktop daycares)",
  "Action.Global.READ_PLACEMENT_SKETCHING_REPORT": "Yleinen: lue sijoitushahmotelma -raportti",
  "Action.Global.READ_PRESCHOOL_ABSENCE_REPORT_FOR_AREA": "Yleinen: lue (preschool absence report for area)",
  "Action.Global.READ_RAW_REPORT": "Yleinen: lue raakadata-raportti",
  "Action.Global.READ_SELECTABLE_FINANCE_DECISION_HANDLERS": "Yleinen: lue (selectable finance decision handlers)",
  "Action.Global.READ_SERVICE_NEED_OPTIONS": "Yleinen: lue (service need options)",
  "Action.Global.READ_SERVICE_WORKER_APPLICATION_NOTES": "Yleinen: lue palveluohjaajan hakemus­muistiinpanot",
  "Action.Global.READ_SEXTET_REPORT": "Yleinen: lue (sextet report)",
  "Action.Global.READ_SPECIAL_DIET_LIST": "Yleinen: lue (special diet list)",
  "Action.Global.READ_SYSTEM_NOTIFICATIONS": "Yleinen: lue (system notifications)",
  "Action.Global.READ_TAMPERE_REGIONAL_SURVEY_REPORT": "Yleinen: lue Tampereen seudun kysely -raportti",
  "Action.Global.READ_UNITS": "Yleinen: lue yksiköt",
  "Action.Global.READ_UNITS_REPORT": "Yleinen: lue (units report)",
  "Action.Global.READ_UNIT_FEATURES": "Yleinen: lue (unit features)",
  "Action.Global.READ_VARDA_REPORT": "Yleinen: lue (varda report)",
  "Action.Global.READ_VOUCHER_VALUES": "Yleinen: lue (voucher values)",
  "Action.Global.REPORTS_PAGE": "Raportit (sivu)",
  "Action.Global.SEARCH_EMPLOYEES": "Yleinen: hae työntekijät",
  "Action.Global.SEARCH_FEE_DECISIONS": "Yleinen: hae maksupäätökset",
  "Action.Global.SEARCH_INVOICES": "Yleinen: hae laskut",
  "Action.Global.SEARCH_PAYMENTS": "Yleinen: hae maksut",
  "Action.Global.SEARCH_PEOPLE": "Yleinen: hae (people)",
  "Action.Global.SEARCH_PEOPLE_UNRESTRICTED": "Yleinen: hae (people unrestricted)",
  "Action.Global.SEARCH_VOUCHER_VALUE_DECISIONS": "Yleinen: hae arvopäätökset",
  "Action.Global.SEND_JAMIX_ORDERS": "Yleinen: lähetä (jamix orders)",
  "Action.Global.SEND_PATU_REPORT": "Yleinen: lähetä Patu-raportti",
  "Action.Global.SETTINGS_PAGE": "Asetukset (sivu)",
  "Action.Global.SUBMIT_PATU_REPORT": "Yleinen: lähetä Patu-raportti",
  "Action.Global.UNITS_PAGE": "Yksiköt (sivu)",
  "Action.Global.UNIT_FEATURES_PAGE": "Yksikön ominaisuudet (sivu)",
  "Action.Global.UPDATE_HOLIDAY_PERIOD": "Yleinen: päivitä lomakausi",
  "Action.Global.UPDATE_HOLIDAY_QUESTIONNAIRE": "Yleinen: päivitä lomakysely",
  "Action.Global.UPDATE_SETTINGS": "Yleinen: päivitä asetukset",
  "Action.Global.UPDATE_SYSTEM_NOTIFICATION": "Yleinen: päivitä (system notification)",
  "Action.Global.UPDATE_VOUCHER_VALUE": "Yleinen: päivitä (voucher value)",
  "Action.Global.VARDA_OPERATIONS": "Varda-operaatiot",
  "Action.Global.WRITE_DECISION_REASONINGS": "Kirjoita päätöksen perustelut",
  "Action.Global.WRITE_SERVICE_WORKER_APPLICATION_NOTES": "Kirjoita palveluohjaajan hakemus­muistiinpanot",
  "Action.Group.CREATE_ABSENCES": "Ryhmä: luo poissaolot",
  "Action.Group.CREATE_CALENDAR_EVENT": "Ryhmä: luo (calendar event)",
  "Action.Group.CREATE_CARETAKERS": "Ryhmä: luo ammattilaiset",
  "Action.Group.CREATE_CHILD_DOCUMENTS": "Ryhmä: luo (child documents)",
  "Action.Group.CREATE_NOTE": "Ryhmä: luo muistiinpano",
  "Action.Group.DELETE": "Ryhmä: poista",
  "Action.Group.DELETE_ABSENCES": "Ryhmä: poista poissaolot",
  "Action.Group.DELETE_CARETAKERS": "Ryhmä: poista ammattilaiset",
  "Action.Group.MARK_ARRIVAL": "Ryhmä: merkitse (arrival)",
  "Action.Group.MARK_DEPARTURE": "Ryhmä: merkitse (departure)",
  "Action.Group.MARK_EXTERNAL_ARRIVAL": "Ryhmä: merkitse (external arrival)",
  "Action.Group.MARK_EXTERNAL_DEPARTURE": "Ryhmä: merkitse (external departure)",
  "Action.Group.NEKKU_MANUAL_ORDER": "Ryhmä: Nekun manuaalinen tilaus",
  "Action.Group.READ_ABSENCES": "Ryhmä: lue poissaolot",
  "Action.Group.READ_CARETAKERS": "Ryhmä: lue ammattilaiset",
  "Action.Group.READ_CITIZEN_DOCUMENT_RESPONSE_REPORT": "Ryhmä: lue (citizen document response report)",
  "Action.Group.READ_NOTES": "Ryhmä: lue muistiinpanot",
  "Action.Group.READ_STAFF_ATTENDANCES": "Ryhmä: lue henkilökunnan läsnäolot",
  "Action.Group.RECEIVE_PUSH_NOTIFICATIONS": "Ryhmä: vastaanota (push notifications)",
  "Action.Group.UPDATE": "Ryhmä: päivitä",
  "Action.Group.UPDATE_CARETAKERS": "Ryhmä: päivitä ammattilaiset",
  "Action.Group.UPDATE_STAFF_ATTENDANCES": "Ryhmä: päivitä henkilökunnan läsnäolot",
  "Action.GroupNote.DELETE": "Ryhmämuistiinpano: poista",
  "Action.GroupNote.UPDATE": "Ryhmämuistiinpano: päivitä",
  "Action.GroupPlacement.DELETE": "Ryhmäsijoitus: poista",
  "Action.GroupPlacement.UPDATE": "Ryhmäsijoitus: päivitä",
  "Action.Income.DELETE": "Tulo: poista",
  "Action.Income.UPDATE": "Tulo: päivitä",
  "Action.Income.UPLOAD_ATTACHMENT": "Tulot: lataa liite",
  "Action.IncomeStatement.READ": "Tuloilmoitus: lue",
  "Action.IncomeStatement.UPDATE_HANDLED": "Tuloilmoitus: päivitä (handled)",
  "Action.IncomeStatement.UPLOAD_ATTACHMENT": "Tuloselvitys: lataa liite",
  "Action.Invoice.DELETE": "Lasku: poista",
  "Action.Invoice.MARK_SENT": "Lasku: merkitse (sent)",
  "Action.Invoice.READ": "Lasku: lue",
  "Action.Invoice.RESEND": "Lasku: lähetä uudelleen",
  "Action.Invoice.SEND": "Lasku: lähetä",
  "Action.Invoice.UPLOAD_ATTACHMENT": "Lasku: lataa liite",
  "Action.InvoiceCorrection.DELETE": "Laskukorjaus: poista",
  "Action.InvoiceCorrection.UPDATE_NOTE": "Laskukorjaus: päivitä muistiinpano",
  "Action.MessageAccount.ACCESS": "Viestitili: käytä",
  "Action.MobileDevice.DELETE": "Mobiililaite: poista",
  "Action.MobileDevice.UPDATE_NAME": "Mobiililaite: päivitä (name)",
  "Action.OtherAssistanceMeasure.DELETE": "Muu tukitoimi: poista",
  "Action.OtherAssistanceMeasure.READ": "Muu tukitoimi: lue",
  "Action.OtherAssistanceMeasure.UPDATE": "Muu tukitoimi: päivitä",
  "Action.Pairing.POST_RESPONSE": "Mobiililaitepariutus: lähetä vastaus",
  "Action.Parentship.DELETE": "Lapsi-vanhempi-suhde: poista",
  "Action.Parentship.DELETE_CONFLICTED_PARENTSHIP": "Lapsi-vanhempi-suhde: poista (conflicted parentship)",
  "Action.Parentship.RETRY": "Lapsi-vanhempi-suhde: yritä uudelleen",
  "Action.Parentship.UPDATE": "Lapsi-vanhempi-suhde: päivitä",
  "Action.Partnership.DELETE": "Puolisosuhde: poista",
  "Action.Partnership.RETRY": "Puolisosuhde: yritä uudelleen",
  "Action.Partnership.UPDATE": "Puolisosuhde: päivitä",
  "Action.Payment.CONFIRM": "Maksu: vahvista",
  "Action.Payment.DELETE": "Maksu: poista",
  "Action.Payment.REVERT_TO_DRAFT": "Maksu: palauta luonnokseksi",
  "Action.Payment.SEND": "Maksu: lähetä",
  "Action.PedagogicalDocument.CREATE_ATTACHMENT": "Pedagoginen asiakirja: luo liite",
  "Action.PedagogicalDocument.DELETE": "Pedagoginen asiakirja: poista",
  "Action.PedagogicalDocument.UPDATE": "Pedagoginen asiakirja: päivitä",
  "Action.Person.ADD_SSN": "Henkilö: lisää henkilötunnus",
  "Action.Person.CREATE_FINANCE_NOTE": "Henkilö: luo (finance note)",
  "Action.Person.CREATE_FOSTER_PARENT_RELATIONSHIP": "Henkilö: luo (foster parent relationship)",
  "Action.Person.CREATE_INCOME": "Henkilö: luo tulot",
  "Action.Person.CREATE_INVOICE_CORRECTION": "Henkilö: luo (invoice correction)",
  "Action.Person.CREATE_PARENTSHIP": "Henkilö: luo lapsi-vanhempi-suhde",
  "Action.Person.CREATE_PARTNERSHIP": "Henkilö: luo puolisosuhde",
  "Action.Person.CREATE_REPLACEMENT_DRAFT_INVOICES": "Henkilö: luo (replacement draft invoices)",
  "Action.Person.DELETE": "Henkilö: poista",
  "Action.Person.DISABLE_SSN_ADDING": "Henkilö: estä henkilötunnuksen lisäys",
  "Action.Person.DOWNLOAD_ADDRESS_PAGE": "Henkilö: lataa (address page)",
  "Action.Person.ENABLE_SSN_ADDING": "Henkilö: salli henkilötunnuksen lisäys",
  "Action.Person.GENERATE_RETROACTIVE_FEE_DECISIONS": "Henkilö: muodosta (retroactive fee decisions)",
  "Action.Person.GENERATE_RETROACTIVE_VOUCHER_VALUE_DECISIONS": "Henkilö: muodosta (retroactive voucher value decisions)",
  "Action.Person.MERGE": "Henkilö: yhdistä",
  "Action.Person.READ": "Henkilö: lue",
  "Action.Person.READ_APPLICATIONS": "Henkilö: lue hakemukset",
  "Action.Person.READ_CHILD_PLACEMENT_PERIODS": "Henkilö: lue lapsen sijoitusjaksot",
  "Action.Person.READ_DECISIONS": "Henkilö: lue päätökset",
  "Action.Person.READ_DEPENDANTS": "Henkilö: lue (dependants)",
  "Action.Person.READ_FAMILY_OVERVIEW": "Henkilö: lue perheen yleisnäkymä",
  "Action.Person.READ_FEE_DECISIONS": "Henkilö: lue maksupäätökset",
  "Action.Person.READ_FINANCE_NOTES": "Henkilö: lue (finance notes)",
  "Action.Person.READ_FOSTER_CHILDREN": "Henkilö: lue sijoituslapset",
  "Action.Person.READ_FOSTER_PARENTS": "Henkilö: lue sijaisvanhemmat",
  "Action.Person.READ_INCOME": "Henkilö: lue tulot",
  "Action.Person.READ_INCOME_NOTIFICATIONS": "Henkilö: lue tuloilmoitukset",
  "Action.Person.READ_INCOME_STATEMENTS": "Henkilö: lue tuloselvitykset",
  "Action.Person.READ_INVOICES": "Henkilö: lue laskut",
  "Action.Person.READ_INVOICE_ADDRESS": "Henkilö: lue laskun osoite",
  "Action.Person.READ_INVOICE_CORRECTIONS": "Henkilö: lue laskukorjaukset",
  "Action.Person.READ_OPH_OID": "Henkilö: lue (oph oid)",
  "Action.Person.READ_PARENTSHIPS": "Henkilö: lue lapsi-vanhempi-suhteet",
  "Action.Person.READ_PARTNERSHIPS": "Henkilö: lue puolisosuhteet",
  "Action.Person.READ_TIMELINE": "Henkilö: lue (timeline)",
  "Action.Person.READ_VOUCHER_VALUE_DECISIONS": "Henkilö: lue arvopäätökset",
  "Action.Person.UPDATE": "Henkilö: päivitä",
  "Action.Person.UPDATE_EVAKA_RIGHTS": "Henkilö: päivitä (evaka rights)",
  "Action.Person.UPDATE_FROM_VTJ": "Henkilö: päivitä (from vtj)",
  "Action.Person.UPDATE_INVOICE_ADDRESS": "Henkilö: päivitä laskun osoite",
  "Action.Person.UPDATE_OPH_OID": "Henkilö: päivitä (oph oid)",
  "Action.Person.UPDATE_PERSONAL_DETAILS": "Henkilö: päivitä (personal details)",
  "Action.Placement.CREATE_GROUP_PLACEMENT": "Sijoitus: luo ryhmäsijoitus",
  "Action.Placement.CREATE_SERVICE_NEED": "Sijoitus: luo palveluntarve",
  "Action.Placement.DELETE": "Sijoitus: poista",
  "Action.Placement.UPDATE": "Sijoitus: päivitä",
  "Action.PreschoolAssistance.DELETE": "Esiopetuksen tuki: poista",
  "Action.PreschoolAssistance.READ": "Esiopetuksen tuki: lue",
  "Action.PreschoolAssistance.UPDATE": "Esiopetuksen tuki: päivitä",
  "Action.PreschoolTerm.DELETE": "Esiopetuskausi: poista",
  "Action.PreschoolTerm.UPDATE": "Esiopetuskausi: päivitä",
  "Action.ServiceApplication.ACCEPT": "Palveluhakemus: hyväksy",
  "Action.ServiceApplication.REJECT": "Palveluhakemus: hylkää",
  "Action.ServiceNeed.DELETE": "Palveluntarve: poista",
  "Action.ServiceNeed.UPDATE": "Palveluntarve: päivitä",
  "Action.Unit.ACCEPT_PLACEMENT_PROPOSAL": "Yksikkö: hyväksy (placement proposal)",
  "Action.Unit.CREATE_CALENDAR_EVENT": "Yksikkö: luo (calendar event)",
  "Action.Unit.CREATE_GROUP": "Yksikkö: luo ryhmä",
  "Action.Unit.CREATE_MOBILE_DEVICE_PAIRING": "Yksikkö: luo mobiililaitepariutus",
  "Action.Unit.CREATE_PLACEMENT": "Yksikkö: luo sijoitus",
  "Action.Unit.CREATE_TEMPORARY_EMPLOYEE": "Yksikkö: luo tilapäinen työntekijä",
  "Action.Unit.DELETE_TEMPORARY_EMPLOYEE": "Yksikkö: poista tilapäinen työntekijä",
  "Action.Unit.INSERT_ACL_EARLY_CHILDHOOD_EDUCATION_SECRETARY": "Yksikkö: lisää (acl early childhood education secretary)",
  "Action.Unit.INSERT_ACL_SPECIAL_EDUCATION_TEACHER": "Yksikkö: lisää (acl special education teacher)",
  "Action.Unit.INSERT_ACL_STAFF": "Yksikkö: lisää (acl staff)",
  "Action.Unit.INSERT_ACL_UNIT_SUPERVISOR": "Yksikkö: lisää (acl unit supervisor)",
  "Action.Unit.READ": "Yksikkö: lue",
  "Action.Unit.READ_ABSENCE_APPLICATIONS": "Yksikkö: lue (absence applications)",
  "Action.Unit.READ_ACL": "Yksikkö: lue (acl)",
  "Action.Unit.READ_APPLICATIONS_AND_PLACEMENT_PLANS": "Yksikkö: lue (applications and placement plans)",
  "Action.Unit.READ_APPLICATIONS_REPORT": "Yksikkö: lue (applications report)",
  "Action.Unit.READ_ASSISTANCE_NEEDS_AND_ACTIONS_REPORT": "Yksikkö: lue tuen tarpeet ja tukitoimet -raportti",
  "Action.Unit.READ_ASSISTANCE_NEEDS_AND_ACTIONS_REPORT_BY_CHILD": "Yksikkö: lue tuen tarpeet ja tukitoimet lapsen mukaan -raportti",
  "Action.Unit.READ_ATTENDANCES": "Yksikkö: lue läsnäolot",
  "Action.Unit.READ_ATTENDANCE_RESERVATIONS": "Yksikkö: lue läsnäolovaraukset",
  "Action.Unit.READ_ATTENDANCE_RESERVATION_REPORT": "Yksikkö: lue läsnäolovaraus-raportti",
  "Action.Unit.READ_CALENDAR_EVENTS": "Yksikkö: lue (calendar events)",
  "Action.Unit.READ_CHILD_AGE_AND_LANGUAGE_REPORT": "Yksikkö: lue (child age and language report)",
  "Action.Unit.READ_CHILD_ATTENDANCES": "Yksikkö: lue lapsen läsnäolot",
  "Action.Unit.READ_CHILD_CAPACITY_FACTORS": "Yksikkö: lue lapsen kapasiteettikertoimet",
  "Action.Unit.READ_CHILD_DOCUMENTS_REPORT": "Yksikkö: lue lapsen asiakirjat -raportti",
  "Action.Unit.READ_CHILD_IN_DIFFERENT_ADDRESS_REPORT": "Yksikkö: lue lapsi eri osoitteessa -raportti",
  "Action.Unit.READ_CHILD_RESERVATIONS": "Yksikkö: lue (child reservations)",
  "Action.Unit.READ_EXCEEDED_SERVICE_NEEDS_REPORT": "Yksikkö: lue ylittyneet palveluntarpeet -raportti",
  "Action.Unit.READ_FAMILY_CONFLICT_REPORT": "Yksikkö: lue perheristiriita -raportti",
  "Action.Unit.READ_FAMILY_CONTACT_REPORT": "Yksikkö: lue (family contact report)",
  "Action.Unit.READ_FAMILY_DAYCARE_MEAL_REPORT": "Yksikkö: lue perhepäivähoidon ateria -raportti",
  "Action.Unit.READ_GROUPS": "Yksikkö: lue ryhmät",
  "Action.Unit.READ_GROUP_DETAILS": "Yksikkö: lue ryhmän yksityiskohdat",
  "Action.Unit.READ_HOLIDAY_PERIOD_ATTENDANCE_REPORT": "Yksikkö: lue lomakauden läsnäolot -raportti",
  "Action.Unit.READ_HOLIDAY_QUESTIONNAIRE_REPORT": "Yksikkö: lue lomakysely-raportti",
  "Action.Unit.READ_MEAL_REPORT": "Yksikkö: lue ateria-raportti",
  "Action.Unit.READ_MISSING_GROUP_PLACEMENTS": "Yksikkö: lue puuttuvat ryhmäsijoitukset",
  "Action.Unit.READ_MISSING_SERVICE_NEED_REPORT": "Yksikkö: lue (missing service need report)",
  "Action.Unit.READ_MOBILE_DEVICES": "Yksikkö: lue mobiililaitteet",
  "Action.Unit.READ_MOBILE_INFO": "Yksikkö: lue (mobile info)",
  "Action.Unit.READ_MOBILE_STATS": "Yksikkö: lue (mobile stats)",
  "Action.Unit.READ_NEKKU_ORDER_REPORT": "Yksikkö: lue (nekku order report)",
  "Action.Unit.READ_OCCUPANCIES": "Yksikkö: lue täyttöasteet",
  "Action.Unit.READ_OCCUPANCY_REPORT": "Yksikkö: lue täyttöaste-raportti",
  "Action.Unit.READ_PARTNERS_IN_DIFFERENT_ADDRESS_REPORT": "Yksikkö: lue puolisot eri osoitteessa -raportti",
  "Action.Unit.READ_PLACEMENT_GUARANTEE_REPORT": "Yksikkö: lue sijoitustakuu-raportti",
  "Action.Unit.READ_PRESCHOOL_ABSENCE_REPORT_FOR_UNIT": "Yksikkö: lue (preschool absence report for unit)",
  "Action.Unit.READ_PRESCHOOL_APPLICATION_REPORT": "Yksikkö: lue esiopetushakemus-raportti",
  "Action.Unit.READ_REALTIME_STAFF_ATTENDANCES": "Yksikkö: lue (realtime staff attendances)",
  "Action.Unit.READ_SERVICE_APPLICATIONS": "Yksikkö: lue (service applications)",
  "Action.Unit.READ_SERVICE_NEED_REPORT": "Yksikkö: lue (service need report)",
  "Action.Unit.READ_SERVICE_VOUCHER_REPORT": "Yksikkö: lue palveluseteli-raportti",
  "Action.Unit.READ_SERVICE_VOUCHER_VALUES_REPORT": "Yksikkö: lue palvelusetelin arvot -raportti",
  "Action.Unit.READ_SERVICE_WORKER_NOTE": "Yksikkö: lue (service worker note)",
  "Action.Unit.READ_STAFF_ATTENDANCES": "Yksikkö: lue henkilökunnan läsnäolot",
  "Action.Unit.READ_STAFF_EMPLOYEE_NUMBER": "Yksikkö: lue (staff employee number)",
  "Action.Unit.READ_STAFF_OCCUPANCY_COEFFICIENTS": "Yksikkö: lue henkilökunnan kapasiteettikertoimet",
  "Action.Unit.READ_STARTING_PLACEMENTS_REPORT": "Yksikkö: lue alkavat sijoitukset -raportti",
  "Action.Unit.READ_TEMPORARY_EMPLOYEE": "Yksikkö: lue tilapäinen työntekijä",
  "Action.Unit.READ_TERMINATED_PLACEMENTS": "Yksikkö: lue päättyneet sijoitukset",
  "Action.Unit.READ_TITANIA_ERRORS": "Yksikkö: lue (titania errors)",
  "Action.Unit.READ_TRANSFER_APPLICATIONS": "Yksikkö: lue siirtohakemukset",
  "Action.Unit.READ_UNIT_RESERVATION_STATISTICS": "Yksikkö: lue (unit reservation statistics)",
  "Action.Unit.READ_UNREAD_MESSAGES": "Yksikkö: lue (unread messages)",
  "Action.Unit.SET_SERVICE_WORKER_NOTE": "Yksikkö: aseta (service worker note)",
  "Action.Unit.UPDATE": "Yksikkö: päivitä",
  "Action.Unit.UPDATE_ACL_EARLY_CHILDHOOD_EDUCATION_SECRETARY": "Yksikkö: päivitä (acl early childhood education secretary)",
  "Action.Unit.UPDATE_ACL_SCHEDULED": "Yksikkö: päivitä (acl scheduled)",
  "Action.Unit.UPDATE_ACL_SPECIAL_EDUCATION_TEACHER": "Yksikkö: päivitä (acl special education teacher)",
  "Action.Unit.UPDATE_ACL_STAFF": "Yksikkö: päivitä (acl staff)",
  "Action.Unit.UPDATE_ACL_UNIT_SUPERVISOR": "Yksikkö: päivitä (acl unit supervisor)",
  "Action.Unit.UPDATE_CHILD_ATTENDANCES": "Yksikkö: päivitä lapsen läsnäolot",
  "Action.Unit.UPDATE_FEATURES": "Yksikkö: päivitä (features)",
  "Action.Unit.UPDATE_STAFF_ATTENDANCES": "Yksikkö: päivitä henkilökunnan läsnäolot",
  "Action.Unit.UPDATE_STAFF_GROUP_ACL": "Yksikkö: päivitä (staff group acl)",
  "Action.Unit.UPDATE_TEMPORARY_EMPLOYEE": "Yksikkö: päivitä tilapäinen työntekijä",
  "Action.Unit.UPSERT_STAFF_OCCUPANCY_COEFFICIENTS": "Yksikkö: tallenna henkilökunnan kapasiteettikertoimet",
  "Action.VoucherValueDecision.ARCHIVE": "Arvopäätös: arkistoi",
  "Action.VoucherValueDecision.IGNORE": "Arvopäätös: ohita",
  "Action.VoucherValueDecision.READ": "Arvopäätös: lue",
  "Action.VoucherValueDecision.READ_METADATA": "Arvopäätös: lue (metadata)",
  "Action.VoucherValueDecision.UNIGNORE": "Arvopäätös: kumoa ohitus",
  "Action.VoucherValueDecision.UPDATE": "Arvopäätös: päivitä",
};

/**
 * Palauttaa kategorialle suomenkielisen otsikon, tai fallbackina annetun ohjelmointi-nimen.
 */
export function categoryLabel(category: string): string {
  return CATEGORY_LABELS[category] ?? category;
}

/**
 * Palauttaa actionin suomenkielisen otsikon, tai fallbackina action-shortNamen.
 * (Jos action lisätään koodikantaan ilman, että tämä taulukko päivitetään,
 * käyttöliittymä näyttää teknisen nimen — ei rikkoudu.)
 */
export function actionLabel(actionName: string, shortNameFallback: string): string {
  return ACTION_LABELS[actionName] ?? shortNameFallback;
}

/**
 * Suomenkieliset käännökset kontekstirajoituksille, joita per-kunta-mappaukset
 * lisäävät HasUnitRole/HasGroupRole-sääntöjen perään (esim. inPlacementUnitOfChild).
 * Fallback: alkuperäinen avain palautetaan jos käännöstä ei löydy.
 */
export const CONTEXT_LABELS: Record<string, string> = {
  "inAnyUnit": "missä tahansa omassa yksikössä",
  "inPlacementPlanUnitOfApplication": "vain hakemuksen sijoitussuunnitelman yksikössä",
  "inPlacementUnitOfChild": "vain lapsen sijoitusyksikössä",
  "inPlacementUnitOfChildOfBackupCare": "vain varasijoitetun lapsen sijoitusyksikössä",
  "inUnit": "vain omassa yksikössä",
  "inUnitOfGroup": "vain ryhmän yksikössä",
};

export const PILOT_FEATURE_LABELS: Record<string, string> = {
  "CLUB_VOUCHER": "kerhon palveluseteli",
  "MESSAGING": "viestintä",
  "MOBILE": "mobiili",
  "MOBILE_MESSAGING": "mobiili-viestintä",
  "PLACEMENT_TERMINATION": "sijoituksen päättäminen",
  "PUSH_NOTIFICATIONS": "push-ilmoitukset",
  "RESERVATIONS": "varaukset käytössä",
  "SERVICE_APPLICATIONS": "palveluhakemukset",
  "STAFF_ATTENDANCE_INTEGRATION": "henkilökunnan läsnäolointegraatio",
  "VASU_AND_PEDADOC": "vasu ja pedagogiset asiakirjat",
};

export const PROVIDER_TYPE_LABELS: Record<string, string> = {
  "EXTERNAL_PURCHASED": "ulkoinen ostopalvelu",
  "MUNICIPAL": "kunnallinen",
  "MUNICIPAL_SCHOOL": "kunnallinen koulu",
  "PRIVATE": "yksityinen",
  "PRIVATE_SERVICE_VOUCHER": "yksityinen palveluseteli",
  "PURCHASED": "ostopalvelu",
};

/**
 * Käännä yksi konteksti­rajoitus suomeksi. Tukee kolmea muotoa:
 *   - 'inPlacementUnitOfChild' jne. → suora CONTEXT_LABELS-haku
 *   - 'features=MOBILE,RESERVATIONS' → PilotFeature-arvot käännetään yhteen pilkuilla
 *   - 'providerTypes=MUNICIPAL,PRIVATE' → ProviderType-arvot käännetään yhteen
 * Tunnistamaton muoto palauttaa alkuperäisen merkkijonon (fallback).
 */
export function contextNoteLabel(note: string): string {
  if (CONTEXT_LABELS[note]) return CONTEXT_LABELS[note];
  const featureMatch = note.match(/^features=(.+)$/);
  if (featureMatch) {
    const items = featureMatch[1].split(',').map((f) => PILOT_FEATURE_LABELS[f.trim()] ?? f.trim());
    return `ominaisuudet käytössä: ${items.join(', ')}`;
  }
  const providerMatch = note.match(/^providerTypes=(.+)$/);
  if (providerMatch) {
    const items = providerMatch[1].split(',').map((p) => PROVIDER_TYPE_LABELS[p.trim()] ?? p.trim());
    return `vain palveluntuottajatyypit: ${items.join(', ')}`;
  }
  return note;
}
